spring:
  application:
    name: application
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:http://localhost:9092}
  profiles:
    active: dev

messaging:
  topics:
    transfer:
      name: PCP.TRANSFER
      num-partitions: 1
      replication-factor: 1
      group-id: transfer-group-id

client:
  authorizer:
    url: https://util.devi.tools
    path: /api/v2

server:
  port: 8080
