spring:
  application:
    name: picpay

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/picpay}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}
    template:
      retry:
        enabled: true
        initial-interval: 5s

server:
  servlet:
    context-path: /picpay

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:avalidsecretjwtkeywithatleast256bitstomakerequestsproperly}
    expiration-time: ${JWT_EXPIRATION_TIME:86400000}
  cookie:
    name: ${COOKIE_NAME:access_token}

amqp:
  max-retries: ${MAX_RETRIES_AMQP:5}
  queues:
    transfer:
      name: ${TRANSFER_QUEUE_NAME:AMQP.PCP.TRANSFER}
    notification:
      name: ${NOTIFICATION_QUEUE_NAME:AMQP.PCP.NOTIFICATION}

authorizer:
    url: ${AUTHORIZER_URL:https://util.devi.tools}
    path: ${AUTHORIZER_PATH:api/v2/}

notification:
    url: ${NOTIFICATION_URL:https://util.devi.tools}
    path: ${NOTIFICATION_PATH:api/v1/}

